"""用户级模型配置（BYOK 持久化）：Fernet 加密存储 + 任务运行时覆盖。

智能体速记:
- 密钥只以 Fernet 密文落库（user_model_configs 表，migration 004），绝不存明文。
- Fernet key 来源优先级: 环境变量 CRAYOTTER_BYOK_SECRET >
  文件 CRAYOTTER_BYOK_SECRET_FILE > <CRAYOTTER_RUNTIME_ROOT>/secrets/byok_fernet.key（自动生成，0600）。
- GET 接口只返回掩码预览（sk-****后4位），绝不回传明文/密文 key。
- 任务创建时通过 get_runtime_overrides(user_id) 取解密后的配置，
  走 runtime_manager 已有的 runtime_overrides（BYOK job-scoped，运行后删除 runtime_profile.json）。
"""

from __future__ import annotations

import base64
import logging
import os
import stat
from pathlib import Path
from typing import Any

from cryptography.fernet import Fernet, InvalidToken

from app.backend import db

logger = logging.getLogger(__name__)

_MAX_TEXT_LEN = 256
_MAX_KEY_LEN = 1024

# 可写字段 → (列名, 是否密钥字段)
_FIELDS: dict[str, tuple[str, bool]] = {
    "api_key": ("api_key_enc", True),
    "base_url": ("base_url", False),
    "model_name": ("model_name", False),
    "video_api_key": ("video_api_key_enc", True),
    "video_base_url": ("video_base_url", False),
    "video_model_name": ("video_model_name", False),
    "tts_api_key": ("tts_api_key_enc", True),
    "tts_base_url": ("tts_base_url", False),
    "tts_model_name": ("tts_model_name", False),
}

_fernet: Fernet | None = None


def _load_fernet() -> Fernet:
    global _fernet
    if _fernet is not None:
        return _fernet
    secret = os.environ.get("CRAYOTTER_BYOK_SECRET", "").strip()
    if not secret:
        secret_file = os.environ.get("CRAYOTTER_BYOK_SECRET_FILE", "").strip()
        if not secret_file:
            # 与服务进程共用同一 runtime root 解析，避免不同进程生成不同密钥
            from app.runtime_paths import get_runtime_root
            secret_file = str(get_runtime_root() / "secrets" / "byok_fernet.key")
        path = Path(secret_file)
        if path.exists():
            secret = path.read_text(encoding="utf-8").strip()
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            secret = Fernet.generate_key().decode("ascii")
            path.write_text(secret, encoding="utf-8")
            os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)  # 0600
            logger.info("generated BYOK Fernet key at %s", path)
    try:
        _fernet = Fernet(secret.encode("ascii"))
    except Exception as exc:  # noqa: BLE001 - 配置错误必须显式暴露
        raise RuntimeError("CRAYOTTER_BYOK_SECRET 不是合法的 Fernet key") from exc
    return _fernet


def _encrypt(plain: str) -> str:
    return _load_fernet().encrypt(plain.encode("utf-8")).decode("ascii")


def _decrypt(token: str) -> str:
    if not token:
        return ""
    try:
        return _load_fernet().decrypt(token.encode("ascii")).decode("utf-8")
    except InvalidToken:
        # 显式失败：密钥轮换/数据损坏时绝不静默返回空串当作“未配置”
        raise RuntimeError("用户模型配置解密失败（BYOK 密钥不匹配或数据损坏）")


def _preview(plain: str) -> str:
    if not plain:
        return ""
    tail = plain[-4:] if len(plain) >= 8 else plain[-2:]
    return f"****{tail}"


def _validate_text(field: str, value: str, secret: bool) -> str:
    value = value.strip()
    limit = _MAX_KEY_LEN if secret else _MAX_TEXT_LEN
    if len(value) > limit or "\r" in value or "\n" in value:
        raise ValueError(f"字段 {field} 非法（超长或含换行）")
    if not secret and value and field.endswith("base_url") and not value.startswith(("http://", "https://")):
        raise ValueError(f"字段 {field} 必须是 http(s) URL")
    return value


def _empty_row() -> dict[str, Any]:
    return {"use_own_key": False, **{field: "" for field in _FIELDS}, "updated_at": None}


def _load_row(user_id: str) -> dict[str, Any]:
    with db.get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            """
            SELECT use_own_key, api_key_enc, base_url, model_name,
                   video_api_key_enc, video_base_url, video_model_name,
                   tts_api_key_enc, tts_base_url, tts_model_name, updated_at
            FROM user_model_configs WHERE user_id = %s
            """,
            (user_id,),
        )
        row = cur.fetchone()
    if row is None:
        return _empty_row()
    result: dict[str, Any] = {"use_own_key": bool(row["use_own_key"]), "updated_at": row["updated_at"]}
    for field, (column, secret) in _FIELDS.items():
        stored = row[column] or ""
        result[field] = _decrypt(stored) if secret else stored
    return result


def public_view(user_id: str) -> dict[str, Any]:
    """GET 视图：密钥只给掩码预览，绝不回传明文。"""
    row = _load_row(user_id)
    view: dict[str, Any] = {
        "use_own_key": row["use_own_key"],
        "updated_at": row["updated_at"].isoformat() if row["updated_at"] else None,
    }
    for field, (_, secret) in _FIELDS.items():
        if secret:
            view[f"has_{field}"] = bool(row[field])
            view[f"{field}_preview"] = _preview(row[field])
        else:
            view[field] = row[field]
    return view


def update(user_id: str, patch: dict[str, Any]) -> dict[str, Any]:
    """合并更新。密钥字段语义: 缺省=保持不变, 空串=清除, 其他=覆写。"""
    if not isinstance(patch, dict):
        raise ValueError("请求体必须是 JSON 对象")
    current = _load_row(user_id)

    use_own_key = current["use_own_key"]
    if "use_own_key" in patch:
        use_own_key = bool(patch["use_own_key"])

    merged: dict[str, str] = {}
    for field, (_, secret) in _FIELDS.items():
        if field in patch:
            value = patch[field]
            if not isinstance(value, str):
                raise ValueError(f"字段 {field} 必须是字符串")
            merged[field] = _validate_text(field, value, secret)
        else:
            merged[field] = current[field]

    if use_own_key and not merged["api_key"]:
        raise ValueError("启用“使用自己的 API”前必须先填写 API Key")

    assignments = {
        "use_own_key": use_own_key,
        **{column: (_encrypt(merged[field]) if secret and merged[field] else ("" if secret else merged[field]))
           for field, (column, secret) in _FIELDS.items()},
    }
    with db.get_connection() as conn, conn.cursor() as cur:
        cur.execute(
            """
            INSERT INTO user_model_configs (
                user_id, use_own_key, api_key_enc, base_url, model_name,
                video_api_key_enc, video_base_url, video_model_name,
                tts_api_key_enc, tts_base_url, tts_model_name
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (user_id) DO UPDATE SET
                use_own_key = EXCLUDED.use_own_key,
                api_key_enc = EXCLUDED.api_key_enc,
                base_url = EXCLUDED.base_url,
                model_name = EXCLUDED.model_name,
                video_api_key_enc = EXCLUDED.video_api_key_enc,
                video_base_url = EXCLUDED.video_base_url,
                video_model_name = EXCLUDED.video_model_name,
                tts_api_key_enc = EXCLUDED.tts_api_key_enc,
                tts_base_url = EXCLUDED.tts_base_url,
                tts_model_name = EXCLUDED.tts_model_name,
                updated_at = now()
            """,
            (
                user_id,
                assignments["use_own_key"],
                assignments["api_key_enc"],
                assignments["base_url"],
                assignments["model_name"],
                assignments["video_api_key_enc"],
                assignments["video_base_url"],
                assignments["video_model_name"],
                assignments["tts_api_key_enc"],
                assignments["tts_base_url"],
                assignments["tts_model_name"],
            ),
        )
    return public_view(user_id)


def clear(user_id: str) -> None:
    """删除用户配置（回到平台配额）。"""
    with db.get_connection() as conn, conn.cursor() as cur:
        cur.execute("DELETE FROM user_model_configs WHERE user_id = %s", (user_id,))


def get_runtime_overrides(user_id: str) -> dict[str, str]:
    """任务创建用：用户启用自有 key 时返回解密后的运行时覆盖，否则返回空 dict。"""
    row = _load_row(user_id)
    if not row["use_own_key"] or not row["api_key"]:
        return {}
    return {field: row[field] for field in _FIELDS if row[field]}


def _mask_for_debug(token: str) -> str:
    """仅测试/调试用：确认密文形态（gAAA 前缀）且不泄露明文。"""
    return base64.urlsafe_b64encode(token.encode("ascii"))[:8].decode("ascii") if token else ""
